Repository GoldKing9/FiveGuys_Backend, pull requests merged in 2023-09, with the labels that each got.

#13 [feat] 파일 및 폴더 생성 및 삭제 및 읽기 구현
  webide/build.gradle
  webide/src/main/java/fiveguys/webide/api/project/controller/ProjectController.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/FileCreateRequest.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/FolderCreateRequest.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/FileReadResponse.java
  webide/src/main/java/fiveguys/webide/api/project/service/ProjectService.java
  webide/src/main/java/fiveguys/webide/config/S3/S3Config.java
Labels: 고혁진

#14 [feat] 레포 생성 api 구현 #12
  webide/build.gradle
  webide/src/main/java/fiveguys/webide/api/project/controller/ProjectController.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/FileTreeResponse.java
  webide/src/main/java/fiveguys/webide/api/project/service/ProjectService.java
  webide/src/main/java/fiveguys/webide/domain/project/Project.java
Labels: 백엔드_구현

#17 [feat] 레포 삭제 api 구현 #16
  webide/src/main/java/fiveguys/webide/api/project/controller/ProjectController.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/ChangeRepoNameRequest.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/CreateRepoResponse.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/InvitedRepoInfo.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/InvitedRepoListResponse.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/InvitedUser.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/MyRepoListResponse.java
  webide/src/main/java/fiveguys/webide/api/project/dto/response/RepoInfo.java
  webide/src/main/java/fiveguys/webide/api/project/service/ProjectService.java
  webide/src/main/java/fiveguys/webide/common/error/ErrorCode.java
  webide/src/main/java/fiveguys/webide/domain/project/Project.java
  webide/src/main/java/fiveguys/webide/repository/invite/InviteRepository.java
  webide/src/main/java/fiveguys/webide/repository/invite/InviteRepositoryCustom.java
  webide/src/main/java/fiveguys/webide/repository/invite/InviteRepositoryImpl.java
  webide/src/main/java/fiveguys/webide/repository/project/ProjectRepository.java
Labels: 백엔드_구현

#24 [Feat] 폴더 및 파일 이름 내용 수정 api 구현
  webide/src/main/java/fiveguys/webide/api/project/controller/ProjectController.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/FileNewBodyRequest.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/FileRenameRequest.java
  webide/src/main/java/fiveguys/webide/api/project/dto/request/FolderRenameRequest.java
  webide/src/main/java/fiveguys/webide/api/project/service/ProjectService.java
Labels: 고혁진, 백엔드_구현
